# Generated by Django 6.0.4 on 2026-05-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('book_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='genre.genre')),
                ('book_writers', models.ManyToManyField(related_name='writebook', to='writer.writer')),
            ],
        ),
    ]
