# Generated by Django 6.0.4 on 2026-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(choices=[('BR', 'Brasil'), ('USA', 'Estados Unidos'), ('PT', 'Portugal'), ('DE', 'Alemanha'), ('FR', 'Franca'), ('UK', 'Reino Unido')])),
            ],
        ),
    ]
